# ========================================================================
# Conexión a NEON - Perfil de Desarrollo (Diego)
# ========================================================================
spring.datasource.url=jdbc:postgresql://ep-shy-night-ac8xyva7-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}